site_name: adun's documentation project
theme:
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo.png
  palette:
    primary: blue grey
  features:
      - toc.integrate
nav:
  - Home: 'index.md'
  - Raspberry Pi: 'rpi.md'
  - Programming:
    - 'Clean Code': 'programming/clean_code.md'
